server/src/testflinger/oidc/views.py
# Copyright (C) 2023-2024 Canonical
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""OIDC related views for authenticated application."""

import logging

from authlib.integrations.base_client.errors import (
    MismatchingStateError,
    OAuthError,
)
from flask import (
    Blueprint,
    current_app,
    redirect,
    session,
    url_for,
)

from testflinger.database import register_web_client

oidc_views = Blueprint("oidc", __name__)

logger = logging.getLogger(__name__)


@oidc_views.route("/callback")
def callback():
    """Redirect callback from OIDC Provider."""
    try:
        token = current_app.oauth.oidc.authorize_access_token()
        session["user"] = token["userinfo"]["name"]
        register_web_client(token)
    except (MismatchingStateError, OAuthError) as err:
        logger.warning("Oauth error during authentication: %s", str(err))
    return redirect(url_for("testflinger.home"))


@oidc_views.route("/login")
def login():
    """Redirects user to OIDC provider for authentication."""
    try:
        return current_app.oauth.oidc.authorize_redirect(
            redirect_uri=url_for("oidc.callback", _external=True)
        )
    except OAuthError:
        return redirect(url_for("testflinger.home"))


@oidc_views.route("/logout")
def logout():
    """Terminate user session and from the OIDC provider."""
    session.clear()
    return redirect(url_for("testflinger.home"))

server/src/testflinger/views.py
# Copyright (C) 2023-2024 Canonical
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""Additional views not associated with the API."""

from datetime import datetime, timedelta, timezone
from http import HTTPStatus

from flask import (
    Blueprint,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from prometheus_client import generate_latest

from testflinger import database
from testflinger.database import mongo
from testflinger.logs import MongoLogHandler

views = Blueprint("testflinger", __name__)


@views.route("/")
def home():
    """Home view."""
    return redirect(url_for("testflinger.agents"))


@views.route("/metrics")
def metrics():
    """Return Prometheus metrics."""
    return generate_latest()


@views.route("/agents")
def agents():
    """Agents view."""
    agent_info = mongo.db.agents.find()
    return render_template("agents.html", agents=agent_info)


@views.route("/agents/<agent_id>")
def agent_detail(agent_id):
    """Agent detail view."""
    default_start_date = (
        datetime.now(tz=timezone.utc) - timedelta(days=2)
    ).strftime("%Y-%m-%d")
    default_stop_date = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    start_date = request.args.get("start", default_start_date)
    stop_date = request.args.get("stop", default_stop_date)

    # Convert start and stop dates to datetime objects for the query
    start_datetime = datetime.strptime(start_date, "%Y-%m-%d").replace(
        tzinfo=timezone.utc
    )
    stop_datetime = datetime.strptime(stop_date, "%Y-%m-%d").replace(
        tzinfo=timezone.utc
    ) + timedelta(days=1)

    agent_info = mongo.db.agents.find_one({"name": agent_id})
    if not agent_info:
        response = make_response(
            render_template("agent_not_found.html", agent_id=agent_id)
        )
        response.status_code = HTTPStatus.NOT_FOUND
        return response

    restricted_queues = database.get_restricted_queues()
    client_permissions = database.get_restricted_queues_owners()

    agent_info["restricted_to"] = {
        queue: client_permissions.get(queue, [])
        if queue in restricted_queues
        else []
        for queue in agent_info.get("queues", [])
    }

    queue_info = []
    for queue_name in agent_info.pop("queues", []):
        queue_data = mongo.db.queues.find_one({"name": queue_name})
        if not queue_data:
            # If it's not an advertised queue, create some dummy data
            queue_data = {"description": ""}
        queue_data["name"] = queue_name
        queue_data["numjobs"] = database.get_num_incomplete_jobs_on_queue(
            queue_name
        )
        queue_info.append(queue_data)

    agent_info["queues"] = queue_info

    # We want to include the start/stop dates so that default values
    # can be filled in for the date pickers
    agent_info["start"] = start_date
    agent_info["stop"] = stop_date

    agent_info["provision_log"] = database.get_provision_log(
        agent_id,
        start_datetime=start_datetime,
        stop_datetime=stop_datetime,
    )

    if agent_info["provision_log"]:
        agent_info["provision_success_rate"] = int(
            100
            * len(
                [
                    entry
                    for entry in agent_info["provision_log"]
                    if entry["exit_code"] == 0
                ]
            )
            / len(agent_info["provision_log"])
        )
    else:
        # Avoid division by zero
        agent_info["provision_success_rate"] = 0

    return render_template("agent_detail.html", agent=agent_info)


@views.route("/jobs")
def jobs():
    """Jobs view."""
    jobs_data = mongo.db.jobs.find(sort=[("created_at", -1)])
    return render_template("jobs.html", jobs=jobs_data)


@views.route("/jobs/<job_id>")
def job_detail(job_id):
    """Job detail view."""
    job_data = mongo.db.jobs.find_one({"job_id": job_id})
    if not job_data:
        response = make_response(
            render_template("job_not_found.html", job_id=job_id),
            HTTPStatus.NOT_FOUND,
        )
        return response

    if result_data := job_data.get("result_data"):
        if not any(
            key.endswith(("_output", "_serial")) for key in result_data.keys()
        ):
            log_handler = MongoLogHandler(mongo)
            log_handler.format_logs_as_results(job_id, result_data)
    return render_template("job_detail.html", job=job_data)


@views.route("/queues")
def queues():
    """
    Queues view.

    Render a view with all known queues, descriptions if known, and the number
    of jobs in each.
    """
    queue_data = queues_data()
    return render_template("queues.html", queues=queue_data)


def queues_data():
    """Generate data for the queues view, this makes testing easier."""
    # First, get all the advertised queues with descriptions
    queue_data = list(
        mongo.db.queues.find(
            projection={"_id": 0, "name": 1, "description": 1}
        )
    )

    # Get all the queues the agents say they are listening to from agent data
    agent_data = mongo.db.agents.find({}, {"_id": 0, "queues": 1})
    agent_queues_set = {
        queue for agent in agent_data for queue in agent.get("queues", [])
    }
    #    queue for agent in agent_data for queue in agent["queues"]
    advertised_queues_set = {queue["name"] for queue in queue_data}

    # Only keep the ones that weren't also in the advertised queues
    unique_queues_from_agents = agent_queues_set - advertised_queues_set
    for queue_name in unique_queues_from_agents:
        queue_data.append(
            {"name": queue_name, "description": "", "numjobs": 0}
        )

    # Get job counts for each queue
    for queue in queue_data:
        queue["numjobs"] = database.get_num_incomplete_jobs_on_queue(
            queue["name"]
        )
    return queue_data


@views.route("/queues/<queue_name>")
def queue_detail(queue_name):
    """Queue detailed view."""
    queue_data = mongo.db.queues.find_one({"name": queue_name})
    if not queue_data:
        # If it's not an advertised queue, create some dummy data
        queue_data = {"name": queue_name, "description": "No description"}

    # Find all the jobs active jobs in this queue
    job_data = mongo.db.jobs.find(
        {
            "job_data.job_queue": queue_name,
            "result_data.job_state": {
                "$nin": ["complete", "completed", "cancelled"]
            },
        }
    )

    # Get the percentiles of wait times for this queue
    wait_times = database.get_queue_wait_times([queue_name])
    try:
        wait_times = wait_times[0]["wait_times"]
    except (IndexError, KeyError):
        wait_times = []
    queue_percentile_data = database.calculate_percentiles(wait_times)

    # Convert the wait times to human-readable strings
    for key, value in queue_percentile_data.items():
        queue_percentile_data[key] = seconds_to_hms(value)

    agents_data = database.get_agents_on_queue(queue_name)

    return render_template(
        "queue_detail.html",
        queue=queue_data,
        jobs=job_data,
        queue_percentile_data=queue_percentile_data,
        agents=agents_data,
    )


def seconds_to_hms(seconds: float) -> str:
    """Convert seconds to a human-readable string."""
    seconds = int(seconds)
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    seconds = seconds % 60
    return f"{hours:02d}h {minutes:02d}m {seconds:02d}s"

server/src/testflinger/templates/_agents_table.html
<table aria-label="Agents table"
       class="p-table--mobile-card"
       id="agentsTable">
  <thead>
    <tr>
      <th aria-sort="none"
          class="has-overflow"
          style="width:10%"
          use-outcome-sort
          id="agentsOutcomeHeader">
        <span class="p-tooltip--top-left" aria-describedby="tooltip">
          <span class="p-tooltip__message"
                role="tooltip"
                id="tooltip"
                style="text-transform:none;
                       font-weight:400">The number of consecutively successful / failed provisioning attempts</span>
          Outcome
        </span>
      </th>
      <th aria-sort="none" id="agentsNameHeader">Name</th>
      <th aria-sort="none" id="agentsNameHeader">Location</th>
      <th aria-sort="none" id="agentsStateHeader">State</th>
      <th aria-sort="none" id="agentsUpdatedAtHeader">Updated At</th>
      <th>Job ID</th>
    </tr>
  </thead>
  <tbody>
    {% if agents %}
      {% for agent in agents %}
        <tr class="searchable-row">
          <td class="has-overflow" data-heading="Outcome">
            {% if agent.provision_streak_type == "fail" and agent.provision_streak_count > 0 %}
              <span class="p-tooltip--right" aria-describedby="tooltip">
                <i class="p-icon--warning"></i>
                <span class="p-tooltip__message" role="tooltip" id="tooltip">This agent has failed the last {{
                agent.provision_streak_count }} provision attempts</span>
              </span>
              <span class="provision-streak">{{ agent.provision_streak_count }}</span>
            {% elif agent.provision_streak_type == "pass" and agent.provision_streak_count > 0 %}
              <span class="p-tooltip--right" aria-describedby="tooltip">
                <i class="p-icon--success"></i>
                <span class="p-tooltip__message" role="tooltip" id="tooltip">This agent has passed the last {{
                agent.provision_streak_count }} provision attempts</span>
              </span>
              <span class="provision-streak">{{ agent.provision_streak_count }}</span>
            {% endif %}
          </td>
          <td data-heading="Name">
            <a href="{{ url_for('testflinger.agent_detail', agent_id=agent.name) }}">{{ agent.name }}</a>
          </td>
          <td data-heading="Location">{{ agent.location or "unknown" }}</td>
          <td class="has-overflow" data-heading="State">
            <span>{{ agent.state }}</span>
            {% if agent.get('comment') %}
              <span class="p-tooltip--top-left" aria-describedby="state-tooltip">
                <i class="p-icon--information"></i>
                <span class="p-tooltip__message"
                      role="tooltip"
                      id="state-tooltip"
                      style="white-space: nowrap;
                             text-align: left">{{ agent.comment }}</span>
              </span>
            {% endif %}
          </td>
          <td data-heading="Updated At">{{ agent.updated_at.strftime("%Y-%m-%d %H:%M:%S") }}</td>
          <td class="u-align--right u-truncate" data-heading="Job ID">
            <a href="{{ url_for('testflinger.job_detail', job_id=agent.job_id) }}">{{ agent.job_id }}</a>
          </td>
        </tr>
      {% endfor %}
    {% else %}
      <caption>
        <div class="p-strip">
          <div class="row">
            <div class="u-align--right col-4 col-medium-2 col-small-1"></div>
            <div class="u-align--left col-8 col-medium-4 col-small-3">
              <p class="p-heading--4 u-no-margin--bottom">No Agents</p>
              {% if active_page == "agents" %}
                <p>Please create agent hosts with agent configurations to populate this server.</p>
              {% elif active_page == "queues" %}
                <p>No agents detected that serve this queue. Please check the spelling of the queue name.</p>
                <a class="p-button" href="{{ url_for('testflinger.queues') }}">View Queues</a>
              {% endif %}
            </div>
          </div>
        </div>
      </caption>
    {% endif %}
  </tbody>
</table>

server/src/testflinger/templates/_header.html
{%- set nav_bar = [
{
"name": "Agents",
"url": url_for("testflinger.agents")
},
{
"name": "Jobs",
"url": url_for("testflinger.jobs")
},
{
"name": "Queues",
"url": url_for("testflinger.queues")
},
{
"name": "Documentation",
"url": "https://canonical-testflinger.readthedocs-hosted.com"
}
] -%}
{%- set active_page = active_page|default('agents') %}
<header id="navigation" class="p-navigation is-dark">
  <div class="p-navigation__row">
    <div class="p-navigation__banner">
      <div class="p-navigation__tagged-logo">
        <a class="p-navigation__link" href="{{ url_for('testflinger.home') }}">
          <div class="p-navigation__logo-tag">
            <!-- djlint:off H006 -->
            <img class="p-navigation__logo-icon"
                 src="https://assets.ubuntu.com/v1/82818827-CoF_white.svg"
                 alt="ubuntu circle of friends logo">
            <!-- djlint:on -->
          </div>
          <span class="p-navigation__logo-title">Testflinger</span>
        </a>
      </div>
      <a href="#navigation" class="p-navigation__toggle--open" title="menu">Menu</a>
      <a href="#navigation-closed"
         class="p-navigation__toggle--close"
         title="close menu">Close menu</a>
    </div>
    <nav class="p-navigation__nav u-image-position"
         aria-label="Main navigation">
      <span class="u-off-screen">
        <a href="#main-content">Jump to main content</a>
      </span>
      <ul class="p-navigation__items">
        {%- for item in nav_bar %}
          <li class="p-navigation__item {% if item.name|lower==active_page %}is-selected{% endif %}">
            <a class="p-navigation__link" href="{{ item.url }}">{{ item.name }}</a>
          </li>
        {%- endfor %}
      </ul>
      {% if oidc_enabled %}
        <ul class="p-navigation__items u-float-right">
          {% if session.user %}
            <li class="p-navigation__item--dropdown-toggle" id="user-menu">
              <a class="p-navigation__link"
                 href="#user-dropdown"
                 aria-controls="user-dropdown">{{ session.user }}</a>
              <ul class="p-navigation__dropdown--right"
                  id="user-dropdown"
                  aria-hidden="true">
                <li>
                  <a href="{{ url_for('oidc.logout') }}"
                     class="p-navigation__dropdown-item">Sign out</a>
                </li>
              </ul>
            </li>
          {% else %}
            <li class="p-navigation__item">
              <a class="p-navigation__link"
                 href="{{ url_for('oidc.login') }}"
                 id="sign-in-button">
                Sign In
                <i class="p-icon--user"></i>
              </a>
            </li>
          {% endif %}
        </ul>
      {% endif %}
    </nav>
  </div>
</header>

server/src/testflinger/templates/agent_detail.html
{% extends "base.html" %}
{% set active_page = "agents" %}
{% set title = "Agent" %}
{% block content %}
  <div class="p-strip is-shallow">
    <div class="row">
      <h1 class="p-heading--3">Agent Detail - {{ agent.name }}</h1>
    </div>
  </div>
  <table aria-label="Agent table" class="p-table--mobile-card">
    <tbody>
      <tr>
        <th scope="row">State</th>
        <td>{{ agent.state }}</td>
      </tr>
      <tr>
        <th scope="row">Location</th>
        <td>{{ agent.location }}</td>
      </tr>
      <tr>
        <th scope="row">Provision Type</th>
        <td>{{ agent.provision_type }}</td>
      </tr>
      <tr>
        <th scope="row">Comment</th>
        <td>{{ agent.comment }}</td>
      </tr>
      <tr>
        <th scope="row">Last updated</th>
        <td>{{ agent.updated_at.strftime("%Y-%m-%d %H:%M:%S") }}</td>
      </tr>
    </tbody>
  </table>
  <h2 class="p-muted-heading">Queues</h2>
  <ul>
    {% for queue in agent.queues %}
      <li>
        <a href="{{ url_for('testflinger.queue_detail', queue_name=queue) }}">{{ queue }}</a>
        {% if agent.restricted_to[queue]|default([]) %}
          <small>(restricted to: {{ agent.restricted_to[queue]|join(", ") }})</small>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  <h2 class="p-muted-heading">Provision History</h2>
  <form action="" method="get" class="p-form--inline">
    <div class="p-form__group">
      <label for="start-date" class="p-form__label">Start Date</label>
      <input type="date"
             id="start-date"
             name="start"
             class="p-form__control"
             value="{{ request.args.get('start', agent.start) }}">
    </div>
    <div class="p-form__group">
      <label for="stop-date" class="p-form__label">Stop Date</label>
      <input type="date"
             id="stop-date"
             name="stop"
             class="p-form__control"
             value="{{ request.args.get('stop', agent.stop) }}">
    </div>
    <button type="submit" class="p-button--positive">Refresh</button>
  </form>
  <div>
    <strong>Provision success rate for this range:</strong> {{ agent.provision_success_rate }}%
  </div>
  <div>
    <table>
      <thead>
        <tr>
          <th style="width: 150pt">Finished At</th>
          <th style="width: 300pt">Job ID</th>
          <th class="p-table__cell--icon-placeholder" style="width: 75pt">Status</th>
          <th>Detail</th>
        </tr>
      </thead>
      <tbody>
        {% for log in agent.provision_log|reverse %}
          <tr>
            <td>{{ log.timestamp.strftime("%Y-%m-%d %H:%M:%S") }}</td>
            <td>
              <a href="{{ url_for('testflinger.job_detail', job_id=log.job_id) }}">{{ log.job_id }}</a>
            </td>
            <td class="u-align--right p-table__cell--icon-placeholder">
              <i class="{{ 'p-icon--success' if log.exit_code==0 else 'p-icon--error' }}"></i>{{ log.exit_code }}
            </td>
            <td>{{ log.detail }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <h2 class="p-muted-heading">Agent Log</h2>
  <div class="p-code-snippet">
    <div class="scrollable">
      <pre class="p-code-snippet__block">
        <code>
            {{ agent.log|join('\n') }}
        </code>
    </pre>
    </div>
  </div>
{% endblock content %}

server/src/testflinger/templates/job_detail.html
{% extends "base.html" %}
{% set active_page = "jobs" %}
{% set title = "Job" %}
{% block content %}
  <div class="p-strip is-shallow">
    <div class="row">
      <h1 class="p-heading--3">Job Detail - {{ job.job_id }}</h1>
    </div>
  </div>
  <table aria-label="Agent table" class="p-table--mobile-card">
    <tbody>
      <tr>
        <th scope="row">Queue</th>
        <td>
          <a href="{{ url_for('testflinger.queue_detail', queue_name=job.job_data.job_queue) }}">{{ job.job_data.job_queue }}</a>
        </td>
      </tr>
      <tr>
        <th scope="row">State</th>
        <td>{{ job.result_data.job_state }}</td>
      </tr>
      <tr>
        <th scope="row">Created At</th>
        <td>{{ job.created_at.strftime("%Y-%m-%d %H:%M:%S") }}</td>
      </tr>
    </tbody>
  </table>
  <h2 class="p-muted-heading" id="job-definition">
    <a href="#job-definition"
       class="p-link--anchor-heading"
       aria-label="Link to Job Definition section">Job Definition</a>
  </h2>
  <div class="p-tabs">
    <div class="p-tabs__list" role="tablist" aria-label="Job Definition tabs">
      <div class="p-tabs__item">
        <button class="p-tabs__link"
                role="tab"
                aria-selected="true"
                aria-controls="provision-data"
                id="provision-data-tab">Provision Data</button>
      </div>
      {% if job.job_data.firmware_update_data %}
        <div class="p-tabs__item">
          <button class="p-tabs__link"
                  role="tab"
                  aria-selected="false"
                  aria-controls="firmware-update-data"
                  id="firmware-update-data-tab">Firmware Update Data</button>
        </div>
      {% endif %}
      {% if job.job_data.test_data %}
        <div class="p-tabs__item">
          <button class="p-tabs__link"
                  role="tab"
                  aria-selected="false"
                  aria-controls="test-data"
                  id="test-data-tab">Test Data</button>
        </div>
      {% endif %}
    </div>
    <div tabindex="0"
         role="tabpanel"
         id="provision-data"
         aria-labelledby="provision-data-tab">
      <div class="p-code-snippet">
        <pre class="p-code-snippet__block--numbered language-yaml">
          <code>
{{ job.job_data.provision_data }}
          </code>
        </pre>
      </div>
    </div>
    {% if job.job_data.firmware_update_data %}
      <div tabindex="0"
           role="tabpanel"
           id="firmware-update-data"
           aria-labelledby="firmware-update-data-tab"
           hidden>
        <div class="p-code-snippet">
          <pre class="p-code-snippet__block--numbered language-yaml">
            <code>
{{ job.job_data.firmware_update_data }}
            </code>
          </pre>
        </div>
      </div>
    {% endif %}
    {% if job.job_data.test_data %}
      <div tabindex="0"
           role="tabpanel"
           id="test-data"
           aria-labelledby="test-data-tab"
           hidden>
        <div class="p-code-snippet">
          <pre class="p-code-snippet__block--numbered language-yaml">
            <code>
{{ job.job_data.test_data.test_cmds }}
            </code>
          </pre>
        </div>
      </div>
    {% endif %}
  </div>
  {% set phases = [
      {"name": "Provision", "id": "provision", "status": job.result_data.get('provision_status'), "output": job.result_data.get('provision_output')},
      {"name": "Firmware Update", "id": "firmware-update", "status": job.result_data.get('firmware_update_status'), "output": job.result_data.get('firmware_output')},
      {"name": "Test", "id": "test", "status": job.result_data.get('test_status'), "output": job.result_data.get('test_output')}
    ] %}
  {% set phases_with_results = phases | selectattr("output") | selectattr("status", "!=", none) | list %}
  {% if phases_with_results %}
    <h2 class="p-muted-heading" id="phase-results">
      <a href="#phase-results"
         class="p-link--anchor-heading"
         aria-label="Link to Phase Results section">Phase Results</a>
    </h2>
    <div class="p-tabs">
      <div class="p-tabs__list" role="tablist" aria-label="Phase Results tabs">
        {% for phase in phases_with_results %}
          <div class="p-tabs__item">
            <button class="p-tabs__link"
                    role="tab"
                    aria-selected="{{ 'true' if loop.first else 'false' }}"
                    aria-controls="{{ phase.id }}-phase"
                    id="{{ phase.id }}-phase-tab">
              {% if phase.status == 0 %}
                <i class="p-icon--success" aria-label="Success"></i>
              {% else %}
                <i class="p-icon--error" aria-label="Error"></i>
              {% endif %}
              {{ phase.name }}
            </button>
          </div>
        {% endfor %}
      </div>
      {% for phase in phases_with_results %}
        <div tabindex="0"
             role="tabpanel"
             id="{{ phase.id }}-phase"
             aria-labelledby="{{ phase.id }}-phase-tab"
             {% if not loop.first %}hidden{% endif %}>
          <div class="{{ 'p-notification--positive' if phase.status == 0 else 'p-notification--negative' }}">
            <div class="p-code-snippet">
              <div class="scrollable">
                <pre class="p-code-snippet__block"><code>{{ phase.output }}</code></pre>
              </div>
            </div>
            <p class="p-notification__response">
              <span class="p-notification__status">Exit Status:</span> {{ phase.status }}
            </p>
          </div>
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endblock content %}

server/src/testflinger/templates/jobs.html
{% extends "base.html" %}
{% set active_page = "jobs" %}
{% set title = "Jobs" %}
{% block content %}
  <div class="p-strip is-shallow">
    <div class="row">
      <h1 class="p-heading--3">Jobs</h1>
    </div>
  </div>
  <table aria-label="Jobs table" class="p-table--mobile-card">
    <thead>
      <tr>
        <th>Job ID</th>
        <th>Queue</th>
        <th style="width: 100pt">State</th>
        <th style="width: 150pt">Created At</th>
      </tr>
    </thead>
    <tbody>
      {% for job in jobs %}
        <tr>
          <td data-heading="Job ID">
            <a href="{{ url_for('testflinger.job_detail', job_id=job.job_id) }}">{{ job.job_id }}</a>
          </td>
          <td data-heading="Queue">
            <a href="{{ url_for('testflinger.queue_detail', queue_name=job.job_data.job_queue) }}">{{ job.job_data.job_queue }}</a>
          </td>
          <td data-heading="State">{{ job.result_data.job_state }}</td>
          <td data-heading="Created At">{{ job.created_at.strftime("%Y-%m-%d %H:%M:%S") }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

server/src/testflinger/templates/queue_detail.html
{% extends "base.html" %}
{% set active_page = "queues" %}
{% set title = "Queue" %}
{% block content %}
  <div class="p-strip is-shallow">
    <div class="row">
      <h1 class="p-heading--3">Queue Detail - {{ queue.name }}</h1>
    </div>
  </div>
  <table aria-label="Queue Details table" class="p-table--mobile-card">
    <tbody>
      <tr>
        <th scope="row">Description</th>
        <td>{{ queue.description }}</td>
      </tr>
    </tbody>
  </table>
  <div class="p-strip is-shallow" style="margin-top: 1rem;">
    <div class="row">
      <h2 class="p-heading--4">Jobs</h2>
    </div>
  </div>
  <table aria-label="Jobs table" class="p-table--mobile-card">
    <thead>
      <tr>
        <th>Job ID</th>
        <th>State</th>
        <th>Created At</th>
      </tr>
    </thead>
    <tbody>
      {% for job in jobs %}
        <tr class="tr-highlight">
          <td data-heading="Job ID">
            <a href="{{ url_for('testflinger.job_detail', job_id=job.job_id) }}">{{ job.job_id }}</a>
          </td>
          <td data-heading="State">{{ job.result_data.job_state }}</td>
          <td data-heading="Created At">{{ job.created_at.strftime("%Y-%m-%d %H:%M:%S") }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="p-strip is-shallow" style="margin-top: 1rem;">
    <div class="row">
      <h2 class="p-heading--4">Agents</h2>
    </div>
  </div>
  {% include "_agents_table.html" %}
  <div class="p-strip is-shallow">
    <div class="row">
      <h2 class="p-heading--4">Wait Time Percentiles</h2>
    </div>
    <table>
      <thead>
        <tr>
          <th>Percentile</th>
          <th>Wait Time</th>
        </tr>
      </thead>
      <tbody>
        {% for percentile, wait_time in queue_percentile_data.items() %}
          <tr>
            <td>{{ percentile }}th</td>
            <td>{{ wait_time }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}